### ISSUE TITLE
units?

### ISSUE THREAD

**Issue by kenman345** [mrodrig/firewalla-apcupsd#2]
I noticed in the conf file that you only know the units for configurations on the MINUTES option. Is this seconds, minutes, milliseconds?

https://github.com/mrodrig/firewalla-apcupsd/blob/5b31ec57ebf00028de14fe2d97a943149187162e/apcupsd.conf#L139

**Comment by mrodrig** [comment]
Hi @kenman345. That `conf` file is directly from the `apcupsd` package, but it appears the `ONBATTERYEVENT` option is specified in seconds.

https://github.com/mrodrig/firewalla-apcupsd/blob/5b31ec57ebf00028de14fe2d97a943149187162e/apcupsd.conf#L130

There's some documentation from the `apcupsd` package on the different parameters here too, which confirms that it's specified in seconds:
https://linux.die.net/man/5/apcupsd.conf

> ONBATTERYDELAY <seconds>
> 
> The number of seconds from when a power failure is detected until apcupsd reacts with an onbattery event.

**Comment by mrodrig** [comment]
I'm going to close this out, but feel free to re-open it if my previous post didn't answer the question. Thanks!
